### ISSUE TITLE
port to python3

### ISSUE THREAD

**Issue by bernhardreiter** [garrison/creoleparser#54]
It would be nice to port creoleparser to python3.

There are already to repos trying to go into that direction:
 * https://github.com/gregbaker/creoleparser
 * https://github.com/whatever-company/creoleparser/tree/py3

**Comment by brondsem** [comment]
@garrison have you considered merging in python3 support?  I think the commits on https://github.com/gregbaker/creoleparser would work well to merge in here and make a pypi release.  (The whatever-company fork is not up-to-date with this repo)

Or if this repo isn't maintained any more, maybe @gregbaker could be given access on pypi to publish a release with his python3 support?

**Comment by gregbaker** [comment]
I created pull request #56, at least.

**Comment by garrison** [comment]
@gregbaker: would you like to be maintainer?  I can transfer the repository to you and figure out how to add you on pypi as well.

**Comment by brondsem** [comment]
IMO there's not much ongoing maintenance to do, as there hasn't been any activity in years, aside from keeping it working on python 3 now.

I would like to see pypi release with the python 3 updates, though.  The version number was already bumped in the pull request, so I think all you'd need to run is:
```
python setup.py sdist
twine upload dist/*  # may need to "pip install twine" if you don't have it
```

**Comment by garrison** [comment]
Done.
